// <auto-generated />
using System;
using CarDealer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarDealer.Persistence.Migrations
{
    [DbContext(typeof(CarDealerContext))]
    [Migration("20201016083402_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarDealer.Domain.Sale.Car.AvailibleCar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AvailibleCars");
                });

            modelBuilder.Entity("CarDealer.Domain.Sale.Car.CarHistoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AvailibleCarId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfItem")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvailibleCarId");

                    b.ToTable("CarHistoryItems");
                });

            modelBuilder.Entity("CarDealer.Domain.Sale.Car.AvailibleCar", b =>
                {
                    b.OwnsOne("CarDealer.Domain.Sale.Car.CarMileage", "CurrentMileage", b1 =>
                        {
                            b1.Property<long>("AvailibleCarId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("MileageInKm")
                                .HasColumnType("int");

                            b1.HasKey("AvailibleCarId");

                            b1.ToTable("AvailibleCars");

                            b1.WithOwner()
                                .HasForeignKey("AvailibleCarId");
                        });

                    b.OwnsOne("CarDealer.Domain.Sale.Car.CarName", "Name", b1 =>
                        {
                            b1.Property<long>("AvailibleCarId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Brand")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Model")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AvailibleCarId");

                            b1.ToTable("AvailibleCars");

                            b1.WithOwner()
                                .HasForeignKey("AvailibleCarId");
                        });

                    b.OwnsOne("CarDealer.Domain.Sale.Car.Engine", "Engine", b1 =>
                        {
                            b1.Property<long>("AvailibleCarId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("AvailibleCarId");

                            b1.ToTable("AvailibleCars");

                            b1.WithOwner()
                                .HasForeignKey("AvailibleCarId");

                            b1.OwnsOne("CarDealer.Domain.Sale.Car.BatteryCapacity", "BatteryCapacity", b2 =>
                                {
                                    b2.Property<long>("EngineAvailibleCarId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("CapacityInKwh")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("EngineAvailibleCarId");

                                    b2.ToTable("AvailibleCars");

                                    b2.WithOwner()
                                        .HasForeignKey("EngineAvailibleCarId");
                                });

                            b1.OwnsOne("CarDealer.Domain.Sale.Car.EngineDisplacement", "EngineCapacity", b2 =>
                                {
                                    b2.Property<long>("EngineAvailibleCarId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("DisplacementInCm3")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("EngineAvailibleCarId");

                                    b2.ToTable("AvailibleCars");

                                    b2.WithOwner()
                                        .HasForeignKey("EngineAvailibleCarId");
                                });

                            b1.OwnsOne("CarDealer.Domain.Sale.Car.EuroStandard", "EuroStandard", b2 =>
                                {
                                    b2.Property<long>("EngineAvailibleCarId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("EngineAvailibleCarId");

                                    b2.ToTable("AvailibleCars");

                                    b2.WithOwner()
                                        .HasForeignKey("EngineAvailibleCarId");
                                });
                        });

                    b.OwnsOne("CarDealer.Domain.SharedKernel.Pln", "BasePrice", b1 =>
                        {
                            b1.Property<long>("AvailibleCarId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("AvailibleCarId");

                            b1.ToTable("AvailibleCars");

                            b1.WithOwner()
                                .HasForeignKey("AvailibleCarId");
                        });
                });

            modelBuilder.Entity("CarDealer.Domain.Sale.Car.CarHistoryItem", b =>
                {
                    b.HasOne("CarDealer.Domain.Sale.Car.AvailibleCar", null)
                        .WithMany("CarHistory")
                        .HasForeignKey("AvailibleCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CarDealer.Domain.Sale.Car.CarMileage", "Mileage", b1 =>
                        {
                            b1.Property<long>("CarHistoryItemId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("MileageInKm")
                                .HasColumnType("int");

                            b1.HasKey("CarHistoryItemId");

                            b1.ToTable("CarHistoryItems");

                            b1.WithOwner()
                                .HasForeignKey("CarHistoryItemId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
